baseURL = "https://www.joehutch.com"
languageCode = "en-us"
title = "Joe Hutchinson"
theme = "aether"
publishDir = "josephhutch.github.io"
disableKinds = ["taxonomies","taxonomyTerm"]

[params]
  brand = "joehutch"
  description = "Joe Hutchinson is a master's student at NC State University studying robotics and artificial intelligence."
  bgimg = "img/ignasi_pattern_s.png"

[markup]
  [markup.highlight]
    style= "igor"