baseURL = "https://www.joehutch.com"
languageCode = "en-us"
title = "Joe Hutchinson"
theme = "aether"
publishDir = "josephhutch.github.io"
disableKinds = ["taxonomies","taxonomyTerm"]

[params]
  brand = "joehutch"
  description = "Joe Hutchinson is a master's student at NC State University studying robotics and artificial intelligence."
  github = "http://github.com/josephhutch"
  linkedin = "http://linkedin.com/in/joehutch"
  headshotimg = "img/faceshot_sm.png"

[markup]
  [markup.highlight]
    style = "igor"