name: GitHub Pages

on:
  push:
    branches:
      - test-horizon

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          token: ${{ secrets.ACCESS_TOKEN }}  # Use a token with access to private submodules
      
      - name: Install Hugo
        run: sudo snap install hugo

      - name: Build Site
        run: hugo --minify

      - name: Generate ICS
        run: |
          python --version
          pip install ics, BeautifulSoup4, requests
          python horizon-feed/core.py ./josephhutch.github.io/horizon-test.ics

      - name: Publish Site
        run: |
          cd josephhutch.github.io
          git init
          git config user.name "Joe Hutchinson"
          git config user.email hutch7995@gmail.com
          git add -A
          git commit -m 'Rebuild with GitHub Actions'
          git push --force https://${{secrets.ACCESS_TOKEN}}@github.com/josephhutch/josephhutch.github.io.git master
