name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          persist-credentials: false

      - uses: jdx/mise-action@v4
        with:
          install_args: "--locked"

      - name: Build Site
        run: hugo --minify

      - name: Publish Site
        run: |
          cd josephhutch.github.io
          git init
          git config user.name "Joe Hutchinson"
          git config user.email hutch7995@gmail.com
          git add -A
          git commit -m 'Rebuild with GitHub Actions'
          git push --force https://${{secrets.ACCESS_TOKEN}}@github.com/josephhutch/josephhutch.github.io.git master
