name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      
      - name: Install Hugo
        run: sudo snap install hugo

      - name: Build Site
        run: hugo --minify

      - name: Publish Site
        run: |
          cd josephhutch.github.io
          git add -A
          git commit -m 'Update site from GitHub Actions'
          git push https://github.com/josephhutch/josephhutch.github.io.git
